pipeline {
    agent any
    tools {
        jdk 'Java_21' // Configure JDK 21 in Jenkins
        maven 'Maven_3.9.11' // Configure Maven in Jenkins
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/sumeetverma07/simple-java-maven-app-may-24.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }
    }
}
